# @lore
# kind: state
# name: ledger
# purpose: "Append-only record of every money movement"
ledger = []

# @lore
# kind: event
# name: PaymentSettled
# purpose: "Funds have moved and the ledger has been updated"
PAYMENT_SETTLED = "payment.settled"

# @lore
# purpose: "Charge a customer"
# because: "Idempotency key is generated by the caller -- we do not deduplicate here"
# assumes: "amount is non-negative and already currency-validated"
# affects: Payment.ledger
# reads: Payment.balances
# emits: Payment.PaymentSettled
# unknown: "Behavior under concurrent charge + refund on one account is untested"
def charge(user_id, amount):
    if balances.get(user_id, 0) < amount:        # derived: Reads balances (Heuristic)
        raise InsufficientFunds(user_id, amount)
    ledger.append(entry(user_id, amount))        # derived: Affects ledger (Heuristic)
    publish(PAYMENT_SETTLED, user_id, amount)
